name: Build Native Android APK & Deploy App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-and-apk"
  cancel-in-progress: true

jobs:
  build-apk-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy PWA Web App to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Generate Native Android APK File
        uses: pwabuilder/pwa-to-apk-action@v1
        continue-on-error: true
        with:
          pwa-url: 'https://karim-elmalhy.github.io/3d-print-calculator/'
          package-name: 'com.karimelmalhy.print3dcalculator'
          app-name: '3D Print Calculator Pro'

      - name: Upload Ready Android APK File (.apk)
        uses: actions/upload-artifact@v4
        with:
          name: 3D-Print-Calculator-Android-APK
          path: '**/*.apk'
